### ISSUE TITLE
Permanently stuck on "Connected! Looking for Spotify activity..."

### ISSUE THREAD

**Issue by niamijneg** [devinbergin/spot-thing#113]
Uninstalled spot-thing and removed it as a developer app on Spotify. When I redownloaded, the prompt for the Client ID and secret does not pop up.

**Comment by devinbergin** [comment]
Navigate to C:\ProgramData\spot-thing and delete the two .json files that are in there and it should reset the setup for you. I'll have to add something for that in the future.

**Comment by niamijneg** [comment]
This fixed it thanks! Great work on this project.

**Comment by devinbergin** [comment]
No problem! and thanks!

**Comment by devinbergin** [comment]
Added a new feature for this today to [reset spot-thing](https://github.com/devinbergin/spot-thing/commit/a82ce353d93f391471be4f4d86e7449d2a9fecfc) with a new button in the menu and on the loading screen. Should make this easier for others.
