### ISSUE TITLE
issue playing on macOS

### ISSUE THREAD

**Issue by bmrobin** [devinbergin/spot-thing#79]
unfortunately i don't have the error message in screenshot anymore, but on macOS to get it running locally i had to include `npm install sharp`.  sharing this issue in case anyone else runs into the same issue.  the way the problem manifested itself was nothing was happening when i clicked "Next" after entering my spotify API credentials

```
"sharp": "^0.31.3"
```

thanks for making this, came here from your reddit post!

**Comment by devinbergin** [comment]
Awesome! I did not try it out on macOS at all so glad to hear that's the only main issue, I'll get that brought into the next version soon.

**Comment by devinbergin** [comment]
Added this into package.json today, better late than never.
